spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/study
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enable: true
    restart:
      enable: true

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      tracing:
        include-parameter-values: true