version: "3.9"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=study
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --data-checksums